### ISSUE TITLE
down all in rpboyer15.github.io/sounds-of-the-storm is deleted

### ISSUE THREAD

**Issue by akiyamaakira** [rpboyer15/sounds-of-the-storm#6]
[Download All](https://mega.nz/#!HptQULxa!lALPjtrQJcOw44IT2EV04wSzRG44zcVTRQRm39_P57c)

**Comment by rpboyer15** [comment]
Thanks for the heads up! Should work fine now.

**Comment by akiyamaakira** [comment]
Thank you! By the way, to my knowledge, hosting those sound files are illegal in many jurisdictions and maybe your contents would be deleted from the github.io and mega.nz in the future due to DMCA (check  out this page https://github.com/gloomyson/StarCraft/archive/master.zip). I suggest just put a sound extract tool or write a extract step would be more appropriate.
